<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <OutputType>Library</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Retro96.TransformSamplePlugin</AssemblyName>
    <RootNamespace>Retro96.TransformSamplePlugin</RootNamespace>
    <BaseOutputPath>$(MSBuildProjectDirectory)\dist\build\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildProjectDirectory)\dist\obj\</BaseIntermediateOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Deterministic>true</Deterministic>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Retro96.Plugin.SDK.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
